/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#121b2f",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#39b8fd",
        "on-tertiary-container": "#009668",
        "on-secondary-container": "#004666",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bdc6e0",
        "on-background": "#0b1c30",
        "on-primary-fixed-variant": "#3d475c",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "secondary-fixed": "#c9e6ff",
        "on-secondary-fixed-variant": "#004c6e",
        "on-tertiary-fixed": "#002113",
        "outline": "#76777d",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "primary-fixed": "#d9e2fd",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "on-surface": "#0b1c30",
        "tertiary-container": "#002113",
        "on-secondary-fixed": "#001e2f",
        "secondary": "#006591",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#4edea3",
        "primary": "#000000",
        "on-primary-container": "#7a849c",
        "outline-variant": "#c6c6cd",
        "primary-container": "#121b2f",
        "on-surface-variant": "#45474d",
        "surface": "#f8f9ff",
        "inverse-surface": "#213145",
        "inverse-primary": "#bdc6e0",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "background": "#f8f9ff",
        "surface-tint": "#555e75",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#89ceff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "3rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "numeric-metric": ["Inter"],
        "body-lg": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["1.125rem", { lineHeight: "1.35", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["2rem", { lineHeight: "1.2", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-lg": ["3rem", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["1.625rem", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.45", letterSpacing: "0em", fontWeight: "400" }],
        "numeric-metric": ["2.25rem", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["1rem", { lineHeight: "1.5", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-caps": ["0.6875rem", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}

